export const translateTimeToItalian = (text: string) => {
  return text
    .replace('just now', 'proprio ora')
    .replace('yesterday', 'ieri')
    .replace('tomorrow', 'domani')
    .replace('seconds', 'secondi')
    .replace(/second\s/, 'secondo ')
    .replace('minutes', 'minuti')
    .replace(/minute\s/, 'minuto ')
    .replace('hours', 'ore')
    .replace(/hour\s/, 'ora ')
    .replace('weeks', 'settimane')
    .replace(/week\s/, 'settimana ')
    .replace('months', 'mesi')
    .replace(/month\s/, 'mese ')
    .replace('years', 'anni')
    .replace(/year\s/, 'anno ')
    .replace('yesterday', 'ieri')
    .replace('from now', '')
    .replace('ago', 'fa')
}
