version: '3'
services:
  gmibot_redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    expose:
      - 6379
    volumes:
      - redis-data:/data

volumes:
  redis-data:
